@extends('layouts.master')
@section('title')
Department List
@endsection
@section('content')
<div class="content-wrapper">
    <section class="content">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                        <div class="col-lg-2">
                            <h5>Department List</h5>
                        </div>
                        <div class="col-lg-10">
                            <div class="ibox-tools">
                                <div class="row">
                                    <div class="col-lg-3">
                                        @if (Session::has('message'))
                                          <div class="text-success">{{ Session::get('message') }}</div>
                                        @endif
                                    </div>
                                    <div class="col-lg-9">
                                        <a href="{{ URL::to('/admin/department/add-new-department') }}" class="pull-right"><span  class="label label-primary">Add New Department</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-responsive table-bordered  table-hover">
                        <thead>
                        <tr>
                            <th>Department ID</th>
                            <th>Department Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach ($departments as $department)
                                <tr>
                                    <td>{{ $department->autoGeneratedDepartmentId }}</td>
                                    <td>{{ $department->departmentName }}</td>
                                    <td>
                                        {{--<a href="" class="label label-primary"><i class="fa fa-edit"></i></a>--}}
                                        <a href="{{ URL::to('admin/department/edit/'.$department->id) }}" class="btn btn-sm btn-info">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        {{--<a href="{{ URL::to('admin/department/show/'.$department->id) }}" class="btn btn-sm btn-success">--}}
                                            {{--<i class="fa fa-eye"></i>--}}
                                        {{--</a>--}}
                                        <a href="{{ URL::to('admin/department/delete/'.$department->id) }}" class="btn btn-sm btn-danger" onClick="return checkDelete();">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="box-footer clearfix">
                        {{ $departments->links() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@endsection