@extends('layouts.master')
@section('title')
Search Application
@endsection
@section('content')
<div class="content-wrapper">
    <section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                        <div class="col-lg-2">
                            <h5>Search Application</h5>
                        </div>
                        <div class="col-lg-10">
                            <div class="ibox-tools">
                                <div class="row">
                                    <div class="col-lg-3">
                                        @if (Session::has('message'))
                                          <div class="text-success">{{ Session::get('message') }}</div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    {!! Form::open(array('url'=>'/apply-to-job/', 'method'=>'POST', 'class'=>'form', 'role'=>'form')) !!}
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                    <select name="departmentId" id="departmentId" class="form-control">
                                        <option value="">Select a Department</option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->autoGeneratedDepartmentId }}">{{ $department->departmentName }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                    <select name="departmentId" id="departmentId" class="form-control">
                                        <option value="">Select a Department</option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->autoGeneratedDepartmentId }}">{{ $department->departmentName }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                   <input type="text" name="departmentName" id="countryName" value="{{ Input::old('departmentName') }}" placeholder="Max Expected Salary" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                   <input type="text" name="departmentName" id="countryName" value="{{ Input::old('departmentName') }}" placeholder="Max Expected Salary" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                   <input type="date" name="departmentName" id="countryName" value="{{ Input::old('departmentName') }}" placeholder="Department Name" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-1 text-center">
                                To
                            </div>

                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                   <input type="date" name="departmentName" id="countryName" value="{{ Input::old('departmentName') }}" placeholder="Min Expected Salary" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentName')){ echo 'has-error'; }?> ">
                                   <button type="submit" class="btn btn-sm btn-white">Search</button>
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        </div>
    </section>
</div>
@endsection