<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDepartmentTable extends Migration
{

    public function up()
    {
        Schema::create('departments', function (Blueprint $table) {
            $table->increments('id');
            $table->string('autoGeneratedDepartmentId', 30);
            $table->string('departmentName')->unique();
            $table->tinyInteger('departmentStatus')->default(1);
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::drop('departments');
    }
}
