<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateJobPostsTable extends Migration {

    public function up()
    {
        Schema::create('job_posts', function (Blueprint $table) {
            $table->increments('id');
            $table->string('autoGeneratedJobId', 30);
            $table->string('departmentId', 30);
            $table->string('jobTitle');
            $table->date('deadline');
            $table->longText('jobDescription');
            $table->tinyInteger('jobStatus')->default(1);
            $table->timestamps();
        });
    }


    public function down()
    {
        Schema::drop('job_posts');
    }
}
