@extends('layouts.frontEndMaster')
@section('sidebar')
<div class="col-lg-3 blog-sidebar">
  <div class="sidebar-module">
    <h4>Categories</h4>
    <ol class="list-unstyled">
    @foreach($departments as $department)
      <li><a href="{{ URL::to('/category/'.$department->autoGeneratedDepartmentId) }}">{{ $department->departmentName }}</a></li>
    @endforeach
    </ol>
  </div>
    {{--<div class="sidebar-module sidebar-module-inset">--}}
      {{--<h4>About</h4>--}}
      {{--<p>Etiam porta.</p>--}}
    {{--</div>--}}
</div>
@endsection