@extends('layouts.master')
@section('title')
Search Job
@endsection
@section('content')
<div class="content-wrapper">
    <section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="row">
                        <div class="col-lg-2">
                            <h5>Search Job</h5>
                        </div>
                        <div class="col-lg-10">
                            <div class="ibox-tools">
                                <div class="row">
                                    <div class="col-lg-3">
                                        @if (Session::has('message'))
                                          <div class="text-success">{{ Session::get('message') }}</div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    {!! Form::open(array('class'=>'form', 'id'=>'jobSearchForm', 'role'=>'form')) !!}
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('jobTitle')){ echo 'has-error'; }?> ">
                                    <input type="text" name="jobTitle" id="jobTitle" value="{{ Input::old('jobTitle') }}" placeholder="Job Title" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group <?php  if($errors->has('departmentId')){ echo 'has-error'; }?> ">
                                    <select name="departmentId" id="departmentId" class="form-control">
                                        <option value="">Select a Department</option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->autoGeneratedDepartmentId }}">{{ $department->departmentName }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group ">
                                   <button type="submit" class="btn btn-sm btn-white">Search</button>
                                </div>
                            </div>
                        </div>
                    {!! Form::close() !!}
                    <script>
                        $("#jobSearchForm").submit(function(event){
                          var jobTitle = $('#jobTitle').val();
                          var departmentId = $('#departmentId').val();
                          var deadLineFrom = $('#deadLineFrom').val();
                          var deadLineTo = $('#deadLineTo').val();
                          var csrf = "{{ csrf_token() }}";
                          $.post("{{ URL::to('/admin/job/ajax-search-job') }}",
                                      {
                                        jobTitle: jobTitle,
                                        departmentId: departmentId,
                                        deadLineFrom: deadLineFrom,
                                        deadLineTo: deadLineTo,
                                        _token: csrf,
                                         headers:{
                                            csrf_token:'<?php echo csrf_token(); ?>'
                                        }
                                      }, function(markup){
                               $('#showSearchResult').html(markup);
                          });
                            event.preventDefault();
                        });
                    </script>
                  <hr/>
                  <div id="showSearchResult"></div>
                </div>
            </div>
        </div>
       </div>
    </section>
</div>
@endsection